# Generated by Django 3.1.5 on 2021-01-06 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_of_employee', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Pay_rolls',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_Leader', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Team_Leaders',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Employee_Id', models.CharField(max_length=60)),
                ('Teams', models.CharField(max_length=60)),
                ('Hourly_rate', models.IntegerField()),
                ('Month', models.CharField(default=1, max_length=20)),
                ('Year', models.IntegerField(default=1)),
                ('Monthly_salary', models.IntegerField(default=1)),
                ('Team_Leader', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Crudapp.team')),
                ('Type_of_employee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Crudapp.payroll')),
            ],
        ),
    ]
